### ISSUE TITLE
Messages selection from main page - error 

### ISSUE THREAD

**Issue by figdot1** [lowag/libremaint#16]
In a completely clean install with just a single location defined I get this error when I select the Messages. I am using PHP 8.2 

Deprecated
: json_decode(): Passing null to parameter #1 ($json) of type string is deprecated in
/home/pgtlvqlm/public_html/libremaint/pages/messages.php
on line
253

Fatal error
: Uncaught mysqli_sql_exception: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ') AND user_id_who_checked=0 ORDER BY message_time DESC' at line 1 in /home/pgtlvqlm/public_html/libremaint/includes/MYSQL_db_class.php:85 Stack trace: #0 /home/pgtlvqlm/public_html/libremaint/includes/MYSQL_db_class.php(85): mysqli_query() #1 /home/pgtlvqlm/public_html/libremaint/pages/messages.php(273): DB->select() #2 /home/pgtlvqlm/public_html/libremaint/pages/lm-body.php(41): require_once('/home/pgtlvqlm/...') #3 /home/pgtlvqlm/public_html/libremaint/index.php(30): require('/home/pgtlvqlm/...') #4 {main} thrown in
/home/pgtlvqlm/public_html/libremaint/includes/MYSQL_db_class.php
on line
85

**Comment by lowag** [comment]
Unfortunately I have no time making a documentation...
The purpose of the "message" page is the following. There can be many IOT devices installed at the machines which can send messages automatically (just an info: e.g. temperature, warning_ something gets strange or error:  a machine can not operate). These messages are stored in the "messages" SQL table. Users only need the infos which are relevant them. Make it more clear in a factory  can more maintenance engineer, or technician  who responsible only for certain machines not the whole factory. However the manager should see everything. That's why if you have recorded assets and you would like to use the "messages" page you have to go to "users" page and then click the "bell" icon next to the user. There you can set which assets belong to that users. The error message you got shows that this has not been set yet.
If a critical message is coming (error) AND you have set a Telegram bot AND the user responsible for that machine AND that user is working then the user or users gets a prompt message to his/her/their phone.
Same is true for the "notification"  page. For this the operators should be registered in the system and and should set their machine(s) . When they report a critical error the system send this message to the certain phones.

**Comment by figdot1** [comment]
OK, understood. I was just trying to find any errors prior to loading some data for our assets. I don't need this functionality so this is not a critical error and I am happy to leave it at the moment. I think it should be left open?

**Comment by lowag** [comment]
You can remove the functions with the following way:
Go to the users' administration page and click first icon next to the serial.
Uncheck the  "SEE_NOTIFICATIONS"  and the "SEE_MESSAGES"
"Submit" logout and login

**Comment by lowag** [comment]
You can remove the functions with the following way:
Go to the users' administration page and click first icon next to the serial.
Uncheck the "SEE_NOTIFICATIONS" and the "SEE_MESSAGES"
"Submit" logout and login
